packageExtensions:
  class-transformer-validator@*:
    dependencies:
      class-transformer: '*'
  debug@*:
    dependencies:
      supports-color: '*'
  typeorm@*:
    dependencies:
      pg: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

pnpMode: strict

yarnPath: .yarn/releases/yarn-3.1.1.cjs
